version: '3.8'

services:
  weather-proxy:
    build: .
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3001/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) }).on('error', () => process.exit(1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.weather-proxy.rule=Host(`weather-proxy.your-domain.com`)"
      - "traefik.http.routers.weather-proxy.tls=true"
      - "traefik.http.routers.weather-proxy.tls.certresolver=letsencrypt"
      - "traefik.http.services.weather-proxy.loadbalancer.server.port=3001"