"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.weatherWebookNorwayV9 = exports.updateWeatherByRegion = exports.updateFastPlannerFlight = exports.updateAlternantOneStep = exports.singleFlightAutomation = exports.pseudoWeatherSegments = exports.getWeatherForAlternates = exports.getGlobalWindsForFlight = exports.flightWeatherRiskTriggeredLightningWaves = exports.flightFuelFpv2 = exports.flightAppUpdateEtdAndCrew = exports.editExistingFlightFp2 = exports.deleteLocationAllgtlocationsV2 = exports.createOrModifyMainFuelFastPlanner = exports.createNewFlightFp2 = exports.createFlightWithWaypoints = exports.createFlightLogObject = exports.calculateSunriseSunset = exports.calculateFlightTimes = exports.buildNewGtLocationsV2 = exports.buildLegsFlightPlanner20 = void 0;
var buildLegsFlightPlanner20_js_1 = require("./actions/buildLegsFlightPlanner20.js");
Object.defineProperty(exports, "buildLegsFlightPlanner20", { enumerable: true, get: function () { return buildLegsFlightPlanner20_js_1.buildLegsFlightPlanner20; } });
var buildNewGtLocationsV2_js_1 = require("./actions/buildNewGtLocationsV2.js");
Object.defineProperty(exports, "buildNewGtLocationsV2", { enumerable: true, get: function () { return buildNewGtLocationsV2_js_1.buildNewGtLocationsV2; } });
var calculateFlightTimes_js_1 = require("./actions/calculateFlightTimes.js");
Object.defineProperty(exports, "calculateFlightTimes", { enumerable: true, get: function () { return calculateFlightTimes_js_1.calculateFlightTimes; } });
var calculateSunriseSunset_js_1 = require("./actions/calculateSunriseSunset.js");
Object.defineProperty(exports, "calculateSunriseSunset", { enumerable: true, get: function () { return calculateSunriseSunset_js_1.calculateSunriseSunset; } });
var createFlightLogObject_js_1 = require("./actions/createFlightLogObject.js");
Object.defineProperty(exports, "createFlightLogObject", { enumerable: true, get: function () { return createFlightLogObject_js_1.createFlightLogObject; } });
var createFlightWithWaypoints_js_1 = require("./actions/createFlightWithWaypoints.js");
Object.defineProperty(exports, "createFlightWithWaypoints", { enumerable: true, get: function () { return createFlightWithWaypoints_js_1.createFlightWithWaypoints; } });
var createNewFlightFp2_js_1 = require("./actions/createNewFlightFp2.js");
Object.defineProperty(exports, "createNewFlightFp2", { enumerable: true, get: function () { return createNewFlightFp2_js_1.createNewFlightFp2; } });
var createOrModifyMainFuelFastPlanner_js_1 = require("./actions/createOrModifyMainFuelFastPlanner.js");
Object.defineProperty(exports, "createOrModifyMainFuelFastPlanner", { enumerable: true, get: function () { return createOrModifyMainFuelFastPlanner_js_1.createOrModifyMainFuelFastPlanner; } });
var deleteLocationAllgtlocationsV2_js_1 = require("./actions/deleteLocationAllgtlocationsV2.js");
Object.defineProperty(exports, "deleteLocationAllgtlocationsV2", { enumerable: true, get: function () { return deleteLocationAllgtlocationsV2_js_1.deleteLocationAllgtlocationsV2; } });
var editExistingFlightFp2_js_1 = require("./actions/editExistingFlightFp2.js");
Object.defineProperty(exports, "editExistingFlightFp2", { enumerable: true, get: function () { return editExistingFlightFp2_js_1.editExistingFlightFp2; } });
var flightAppUpdateEtdAndCrew_js_1 = require("./actions/flightAppUpdateEtdAndCrew.js");
Object.defineProperty(exports, "flightAppUpdateEtdAndCrew", { enumerable: true, get: function () { return flightAppUpdateEtdAndCrew_js_1.flightAppUpdateEtdAndCrew; } });
var flightFuelFpv2_js_1 = require("./actions/flightFuelFpv2.js");
Object.defineProperty(exports, "flightFuelFpv2", { enumerable: true, get: function () { return flightFuelFpv2_js_1.flightFuelFpv2; } });
var flightWeatherRiskTriggeredLightningWaves_js_1 = require("./actions/flightWeatherRiskTriggeredLightningWaves.js");
Object.defineProperty(exports, "flightWeatherRiskTriggeredLightningWaves", { enumerable: true, get: function () { return flightWeatherRiskTriggeredLightningWaves_js_1.flightWeatherRiskTriggeredLightningWaves; } });
var getGlobalWindsForFlight_js_1 = require("./actions/getGlobalWindsForFlight.js");
Object.defineProperty(exports, "getGlobalWindsForFlight", { enumerable: true, get: function () { return getGlobalWindsForFlight_js_1.getGlobalWindsForFlight; } });
var getWeatherForAlternates_js_1 = require("./actions/getWeatherForAlternates.js");
Object.defineProperty(exports, "getWeatherForAlternates", { enumerable: true, get: function () { return getWeatherForAlternates_js_1.getWeatherForAlternates; } });
var pseudoWeatherSegments_js_1 = require("./actions/pseudoWeatherSegments.js");
Object.defineProperty(exports, "pseudoWeatherSegments", { enumerable: true, get: function () { return pseudoWeatherSegments_js_1.pseudoWeatherSegments; } });
var singleFlightAutomation_js_1 = require("./actions/singleFlightAutomation.js");
Object.defineProperty(exports, "singleFlightAutomation", { enumerable: true, get: function () { return singleFlightAutomation_js_1.singleFlightAutomation; } });
var updateAlternantOneStep_js_1 = require("./actions/updateAlternantOneStep.js");
Object.defineProperty(exports, "updateAlternantOneStep", { enumerable: true, get: function () { return updateAlternantOneStep_js_1.updateAlternantOneStep; } });
var updateFastPlannerFlight_js_1 = require("./actions/updateFastPlannerFlight.js");
Object.defineProperty(exports, "updateFastPlannerFlight", { enumerable: true, get: function () { return updateFastPlannerFlight_js_1.updateFastPlannerFlight; } });
var updateWeatherByRegion_js_1 = require("./actions/updateWeatherByRegion.js");
Object.defineProperty(exports, "updateWeatherByRegion", { enumerable: true, get: function () { return updateWeatherByRegion_js_1.updateWeatherByRegion; } });
var weatherWebookNorwayV9_js_1 = require("./actions/weatherWebookNorwayV9.js");
Object.defineProperty(exports, "weatherWebookNorwayV9", { enumerable: true, get: function () { return weatherWebookNorwayV9_js_1.weatherWebookNorwayV9; } });
