"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.$ontologyRid = exports.$osdkMetadata = exports.$Queries = exports.$Objects = exports.User = exports.RegionalWeatherMinimaSettings = exports.NorwayWeatherXv8 = exports.NorwayWeatherSegments = exports.NorwayWeatherDatav2 = exports.MainFuelV2 = exports.MainFlightObjectFp2 = exports.LegObjectOutputObject = exports.InternationalWeather = exports.FuelPolicyBuilder = exports.FlightLogObject = exports.FlightFuelDburbury = exports.BristowHelidecks = exports.Asset = exports.AllGtLocationsV2 = exports.AirportsData = exports.$Interfaces = exports.$Actions = exports.weatherWebookNorwayV9 = exports.updateWeatherByRegion = exports.updateFastPlannerFlight = exports.updateAlternantOneStep = exports.singleFlightAutomation = exports.pseudoWeatherSegments = exports.getWeatherForAlternates = exports.getGlobalWindsForFlight = exports.flightWeatherRiskTriggeredLightningWaves = exports.flightFuelFpv2 = exports.flightAppUpdateEtdAndCrew = exports.editExistingFlightFp2 = exports.deleteLocationAllgtlocationsV2 = exports.createOrModifyMainFuelFastPlanner = exports.createNewFlightFp2 = exports.createFlightWithWaypoints = exports.createFlightLogObject = exports.calculateSunriseSunset = exports.calculateFlightTimes = exports.buildNewGtLocationsV2 = exports.buildLegsFlightPlanner20 = void 0;
var actions_js_1 = require("./ontology/actions.js");
Object.defineProperty(exports, "buildLegsFlightPlanner20", { enumerable: true, get: function () { return actions_js_1.buildLegsFlightPlanner20; } });
Object.defineProperty(exports, "buildNewGtLocationsV2", { enumerable: true, get: function () { return actions_js_1.buildNewGtLocationsV2; } });
Object.defineProperty(exports, "calculateFlightTimes", { enumerable: true, get: function () { return actions_js_1.calculateFlightTimes; } });
Object.defineProperty(exports, "calculateSunriseSunset", { enumerable: true, get: function () { return actions_js_1.calculateSunriseSunset; } });
Object.defineProperty(exports, "createFlightLogObject", { enumerable: true, get: function () { return actions_js_1.createFlightLogObject; } });
Object.defineProperty(exports, "createFlightWithWaypoints", { enumerable: true, get: function () { return actions_js_1.createFlightWithWaypoints; } });
Object.defineProperty(exports, "createNewFlightFp2", { enumerable: true, get: function () { return actions_js_1.createNewFlightFp2; } });
Object.defineProperty(exports, "createOrModifyMainFuelFastPlanner", { enumerable: true, get: function () { return actions_js_1.createOrModifyMainFuelFastPlanner; } });
Object.defineProperty(exports, "deleteLocationAllgtlocationsV2", { enumerable: true, get: function () { return actions_js_1.deleteLocationAllgtlocationsV2; } });
Object.defineProperty(exports, "editExistingFlightFp2", { enumerable: true, get: function () { return actions_js_1.editExistingFlightFp2; } });
Object.defineProperty(exports, "flightAppUpdateEtdAndCrew", { enumerable: true, get: function () { return actions_js_1.flightAppUpdateEtdAndCrew; } });
Object.defineProperty(exports, "flightFuelFpv2", { enumerable: true, get: function () { return actions_js_1.flightFuelFpv2; } });
Object.defineProperty(exports, "flightWeatherRiskTriggeredLightningWaves", { enumerable: true, get: function () { return actions_js_1.flightWeatherRiskTriggeredLightningWaves; } });
Object.defineProperty(exports, "getGlobalWindsForFlight", { enumerable: true, get: function () { return actions_js_1.getGlobalWindsForFlight; } });
Object.defineProperty(exports, "getWeatherForAlternates", { enumerable: true, get: function () { return actions_js_1.getWeatherForAlternates; } });
Object.defineProperty(exports, "pseudoWeatherSegments", { enumerable: true, get: function () { return actions_js_1.pseudoWeatherSegments; } });
Object.defineProperty(exports, "singleFlightAutomation", { enumerable: true, get: function () { return actions_js_1.singleFlightAutomation; } });
Object.defineProperty(exports, "updateAlternantOneStep", { enumerable: true, get: function () { return actions_js_1.updateAlternantOneStep; } });
Object.defineProperty(exports, "updateFastPlannerFlight", { enumerable: true, get: function () { return actions_js_1.updateFastPlannerFlight; } });
Object.defineProperty(exports, "updateWeatherByRegion", { enumerable: true, get: function () { return actions_js_1.updateWeatherByRegion; } });
Object.defineProperty(exports, "weatherWebookNorwayV9", { enumerable: true, get: function () { return actions_js_1.weatherWebookNorwayV9; } });
exports.$Actions = require("./ontology/actions.js");
exports.$Interfaces = require("./ontology/interfaces.js");
var objects_js_1 = require("./ontology/objects.js");
Object.defineProperty(exports, "AirportsData", { enumerable: true, get: function () { return objects_js_1.AirportsData; } });
Object.defineProperty(exports, "AllGtLocationsV2", { enumerable: true, get: function () { return objects_js_1.AllGtLocationsV2; } });
Object.defineProperty(exports, "Asset", { enumerable: true, get: function () { return objects_js_1.Asset; } });
Object.defineProperty(exports, "BristowHelidecks", { enumerable: true, get: function () { return objects_js_1.BristowHelidecks; } });
Object.defineProperty(exports, "FlightFuelDburbury", { enumerable: true, get: function () { return objects_js_1.FlightFuelDburbury; } });
Object.defineProperty(exports, "FlightLogObject", { enumerable: true, get: function () { return objects_js_1.FlightLogObject; } });
Object.defineProperty(exports, "FuelPolicyBuilder", { enumerable: true, get: function () { return objects_js_1.FuelPolicyBuilder; } });
Object.defineProperty(exports, "InternationalWeather", { enumerable: true, get: function () { return objects_js_1.InternationalWeather; } });
Object.defineProperty(exports, "LegObjectOutputObject", { enumerable: true, get: function () { return objects_js_1.LegObjectOutputObject; } });
Object.defineProperty(exports, "MainFlightObjectFp2", { enumerable: true, get: function () { return objects_js_1.MainFlightObjectFp2; } });
Object.defineProperty(exports, "MainFuelV2", { enumerable: true, get: function () { return objects_js_1.MainFuelV2; } });
Object.defineProperty(exports, "NorwayWeatherDatav2", { enumerable: true, get: function () { return objects_js_1.NorwayWeatherDatav2; } });
Object.defineProperty(exports, "NorwayWeatherSegments", { enumerable: true, get: function () { return objects_js_1.NorwayWeatherSegments; } });
Object.defineProperty(exports, "NorwayWeatherXv8", { enumerable: true, get: function () { return objects_js_1.NorwayWeatherXv8; } });
Object.defineProperty(exports, "RegionalWeatherMinimaSettings", { enumerable: true, get: function () { return objects_js_1.RegionalWeatherMinimaSettings; } });
Object.defineProperty(exports, "User", { enumerable: true, get: function () { return objects_js_1.User; } });
exports.$Objects = require("./ontology/objects.js");
exports.$Queries = require("./ontology/queries.js");
var OntologyMetadata_js_1 = require("./OntologyMetadata.js");
Object.defineProperty(exports, "$osdkMetadata", { enumerable: true, get: function () { return OntologyMetadata_js_1.$osdkMetadata; } });
var OntologyMetadata_js_2 = require("./OntologyMetadata.js");
Object.defineProperty(exports, "$ontologyRid", { enumerable: true, get: function () { return OntologyMetadata_js_2.$ontologyRid; } });
